[package]
edition = "2024"
name = "abs_async_iter"
version = "0.1.0"
authors = ["lino <lino_snsalias@outlook.com>"]
description = "ABStraction of STREAM"
repository = "https://github.com/ljsnogard/abs_async_iter"
keywords = ["async", "iter", "traits"]
categories = ["no-std"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
abs_cancel = { git = "https://gitee.com/lino_snsalias/abs_cancel-rs.git" }
